engines:
  csslint:
    enabled: true
    checks:
      gradients:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.css"
exclude_paths:
- "api-docs/"
- "coverage/"
- "jasmine/"
- "node_modules/"
- "test/"
- "testis/"
- "bundle.js"
