engines:
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
      Identical code:
        enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
ratings:
  paths:
  - "server/controllers/*.js"
  - "test/**"
  - "server/migrations/*.js"
  - "**.scss"
exclude_paths:
- "server/seeders/**"
- "server/config/**"
- "api-doc/**"
- "jasmine/**"
- "client/dist/**"
