engines:
  csslint:
    enabled: true
    checks:
      gradients:
        enabled: false
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
ratings:
  paths:
  - "test/server/**/*.js"

exclude_paths:
- "api-docs/"
- "coverage/"
- "jasmine/"

- "bundle.js"
- "client/*"

- "server/*"

- "node_modules/"
- "tests/client"
- "screenshot"