engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
ratings:
  paths:
  - "server/*.js"
  - "server/**/*.js"

exclude_paths:
- "server/seeders/"
- "server/migrations"
- "server/config""
