language: node_js
node_js: "stable"

node_js:
  - node

services:
  - postgresql

before_install:
  - psql -c 'create database PK_dms_test;' -U postgres

after_success:
  - cat coverage/*lcov.info | ./node_modules/.bin/coveralls