sudo: required
dist: trusty
language: node_js
node_js: "6"
services:
  - postgresql
addons:
  - postgresql: "9.6"
before_script:
  - psql -c 'create database pk_docman_test;' -U postgres

script:
  - npm test
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
after_success:
 - npm run coverage


language: node_js
node_js: "stable"

node_js:
  - node

services:
  - postgresql

after_script:
  - npm run coveralls