sudo: required
dist: trusty
language: node_js
node_js: "6"
services:
  - postgresql
addons:
  - postgresql: "9.6"
env:
 - TEST_DBURL=postgres://postgres@localhost:8000/pk_docman_test
branches:
  only:
    - development
before_script:
  - psql -c 'create database pk_docman_testt;' -U postgres

script:
  - npm test
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
after_success:
 - npm run coverage


language: node_js
node_js: "stable"

node_js:
  - node

services:
  - postgresql

before_install:
  - psql -c 'create database dms_test;' -U postgres

after_script:
  - npm run coveralls